
services:
  jira:
    build: Jira/
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/vanilla/application-data/jira:/var/atlassian/application-data/jira
    networks:
      - jira
    links:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/conf.d:/etc/mysql/conf.d
      - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/data:/var/lib/mysql
    networks:
      - jira
    env_file:
      - .my.env

  netshoot:
    image: nicolaka/netshoot
    entrypoint: sleep 600
    networks:
      - jira

networks:
  jira:
