
CREATE USER 'jira'@'%' IDENTIFIED BY '<PASSWORD>';

CREATE DATABASE jiradb CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, ALTER, INDEX
    ON jiradb.* TO 'jira'@'%';

FLUSH PRIVILEGES;
